
## Opacity change between steps while fading in. (0.01 - 1.0, defaults to 0.028)
fade-in-step = 0.03;

# Opacity change between steps while fading out. (0.01 - 1.0, defaults to 0.03)
fade-out-step = 0.03;
backend = "glx"

focus-exclude = [ "class_g = 'rofi'" ];
vsync = true;

detect-rounded-corners = true;


detect-client-opacity = true;

detect-transient = true;

use-damage = false;
blur-method = "dual_kawase";
blur-size = 9;

rules: ({
  match = "class_g = 'Spo'";
  opacity = 0.5;
}

